Miguel hernandez999
ITIC-ITESME/juego-random pull request #15
Opened 2022-12-03 00:45 UTC by MiguelHernandez999

Se agrego un nuevo juego de dados utilizando el módulo random

2022-12-03 00:48 UTC, ingrafaelcr commented
Su codigo esta en revision.

2022-12-03 00:48 UTC, MiguelHernandez999 commented
ok gracias

2022-12-03 00:50 UTC, ingrafaelcr requested changes
Cambia la function dados agregando tu usuario al final

2022-12-03 00:50 UTC, ingrafaelcr commented on juegos.py
> +def dados():
```suggestion
def dados_@usuario():
```

2022-12-03 00:50 UTC, ingrafaelcr commented on juegos.py
> +            dados()
Cambia el usuario.

2022-12-09 23:20 UTC, ingrafaelcr approved these changes
Bien hecho.

2022-12-09 23:23 UTC, merged