Se agrego un nuevo juego de dados utilizando el módulo random
ITIC-ITESME/juego-random pull request #9
Opened 2022-12-02 02:44 UTC by Eliud-jpg

2022-12-02 02:45 UTC, ingrafaelcr commented
Su codigo que encuentra en revision

2022-12-02 02:46 UTC, Eliud-jpg commented
Enterado estoy en espera

2022-12-02 02:49 UTC, ingrafaelcr requested changes
Agrega tu usuario al nombre de la funcion

2022-12-02 02:49 UTC, ingrafaelcr commented on juegos.py
> +def dados():
```suggestion
def dados_@usuario():
```

2022-12-02 02:49 UTC, ingrafaelcr commented on juegos.py
> +            print("\nDados")
Modificar llamada tambien

2022-12-02 03:55 UTC, Eliud-jpg commented on juegos.py
> +            print("\nDados")
Listo esta modificado

2022-12-02 03:59 UTC, Eliud-jpg commented
Termine

2022-12-03 00:25 UTC, ingrafaelcr approved these changes
Bien hecho

2022-12-03 00:25 UTC, merged